// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChatApp.DAL.Entities
{
    public partial class ChatMembers
    {
        public string Id { get; set; }
        public Chat ChatId { get; set; }
        public User UserId { get; set; }
    }
}