// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChatApp.DAL.Entities
{
    public partial class ContactRequest
    {
        public string Id { get; set; }
        public string FromUserId { get; set; }
        public string ToUserId { get; set; }
        public string StatusId { get; set; }
        public DateTime? RequestTime { get; set; }
    }
}