// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChatApp.DAL.Entities
{
    public partial class Contacts
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string ContactUserId { get; set; }
    }
}